[package]
name = "lsl-sys"
version = "0.1.0"
authors = ["Intheon <contact@intheon.io>", "Christian Kothe <christian.kothe@intheon.io>"]
edition = "2018"
description = "Low-level bindings to the system liblsl library (lab streaming layer)."
repository = "https://github.com/intheon/liblsl-rust/"
license = "MIT"
keywords = ["ffi", "lsl"]
categories = ["external-ffi-bindings"]
links = "lsl"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cmake = "0.1.44"


[dependencies]


[features]
default = []

# enable this feature if you want to force a statically linked liblsl (built from source)
force-static = []
