[package]
name = "lsl-sys"
version = "0.1.0"
authors = ["Intheon <contact@intheon.io>", "Christian Kothe <christian.kothe@intheon.io>"]
edition = "2018"
description = "Raw liblsl bindings for rust, used internally by lsl-sys."
repository = "https://github.com/intheon/liblsl-rust/"
license = "MIT"
keywords = ["ffi", "bindings"]
categories = ["external-ffi-bindings"]
# links = "lsl"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
